apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: customer-service
        dapr.io/app-port: "8084"
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "60644"
        dapr.io/unix-domain-socket-path: ""
      labels:
        app: customer-service
    spec:
      containers:
        - env:
            - name: APP_PORT
              value: "8084"
            - name: DAPR_METRICS_PORT
              value: "60644"
            - name: APP_ID
              value: customer-service
            - name: APP_CHANNEL_ADDRESS
          imagePullPolicy: IfNotPresent
          image: customer-service:latest
          name: customer-service
          ports:
            - containerPort: 8084
          resources: {}
#          livenessProbe:
#            httpGet:
#              path: /v1.0/healthz
#              port: 3500
#            initialDelaySeconds: 10
#            periodSeconds: 5