apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: dapr-dev-redis-master.default.svc.cluster.local:6379
    - name: redisPassword
      secretKeyRef:
        name: dapr-dev-redis
        key: redis-password
    - name: actorStateStore
      value: "true"
scopes:
  - order-service
  - inventory-service
  - shipping-service
  - customer-service